kind: Deployment
apiVersion: apps/v1
metadata:
  name: plex
  namespace: default
  labels:
    app: plex
  annotations: ## Add this annotations for keel ##  
    keel.sh/policy: minor
    keel.sh/trigger: poll        
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex     
    spec:
      containers:
      - env:  
#        - name: PLEX_CLAIM
#          value: ##your token##
        - name: PGID
          value: "1000"    
        - name: PUID
          value: "1000" 
        - name: TZ
          value: Asia/Tokyo  
        image: plexinc/pms-docker:latest
        name: plex
        ports:
        - containerPort: 32400
          name: http
          protocol: TCP
        - containerPort: 32469
          name: dlna-tcp
          protocol: TCP
        - containerPort: 1900
          name: dlna-udp 
          protocol: UDP
        - containerPort: 3005
          name: plex-companion
          protocol: TCP
        - containerPort: 5353
          name: discovery-udp
          protocol: UDP
        - containerPort: 32410
          name: gdm1-32410
          protocol: UDP
        - containerPort: 32412
          name: gdm2-32410
          protocol: UDP
        - containerPort: 32413
          name: gdm3-32413
          protocol: UDP
        - containerPort: 32414
          name: gdm4-32414
        resources:
          limits:
            memory: "2000Mi"
          requests:
            memory: "1200Mi" 
        volumeMounts: 
        - name: config
          mountPath: /config
        - name: media
          mountPath: /hdd
        - name: tmp
          mountPath: /temporary
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-plex-database
        - name: media
          persistentVolumeClaim:
            claimName: pvc-plex-media
        - name: tmp
          persistentVolumeClaim:
            claimName: pvc-plex-tmp

---

apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: default
spec:
  selector:
    app: plex
  ports:
  - name: http
    targetPort: 32400
    port: 32400
