kind: Deployment
apiVersion: apps/v1
metadata:
  name: heimdall
  namespace: default
  labels:
    app: heimdall
  annotations: ## Add this annotations for keel ##  
    keel.sh/policy: minor
    keel.sh/trigger: poll    
spec:
  replicas: 1
    strategy:
    type: Recreate
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"    
        - name: PUID
          value: "1000" 
        - name: TZ
          value: Asia/Tokyo 
        name: heimdall
        image: lscr.io/linuxserver/heimdall:latest
        resources:
          limits:
            memory: "100Mi"
          requests:
            memory: "80Mi"
        volumeMounts: 
        - name: config
          mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-heimdall

---

apiVersion: v1
kind: Service
metadata:
  name: heimdall
  namespace: default
spec:
  selector:
    app: heimdall
  ports:
  - name: http
    targetPort: 80
    port: 8000
