apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: nextcloud
  labels:
    app: mariadb
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: "500m"
              memory: "1000Mi"
            requests:
              cpu: "100m"
              memory: "200Mi"
          args:
            - --transaction-isolation=READ-COMMITTED
            - --binlog-format=ROW
            - --max-connections=1000
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mariadb-secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mariadb-secrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: mariadb-secrets
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mariadb-secrets
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: mariadb

---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: nextcloud
type: Opaque
data:
  MYSQL_USER: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DATABASE: bmV4dGNsb3Vk
  MYSQL_PASSWORD: cm9vdA==

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: nextcloud-mariadb

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-mariadb
  namespace: nextcloud
spec:
  capacity:
    storage: 10Gi
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes-volumes/nextcloud/mariadb

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: nextcloud
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
