kind: Deployment
apiVersion: apps/v1
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis
            - name: MYSQL_HOST
              value: mariadb
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mariadb-secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mariadb-secrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: mariadb-secrets
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mariadb-secrets
            - name: NEXTCLOUD_ADMIN_USER
              value: "admin"
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: nextlcoud.sharmahome.info home-macmini 10.0.0.20
            - name: APACHE_BODY_LIMIT
              value: "10737418240"
          image: nextcloud:latest
          name: nextcloud
          lifecycle: ##Optional: should run a nextcloud cronjob for the installed apache browser
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "apt-get update && apt-get install -y openrc && start-stop-daemon --start --background --pidfile /cron.pid --exec /cron.sh"
          resources:
            limits:
              memory: "2000Mi"
              cpu: "1"
            # requests:
            #   memory: "128Mi"
            #   cpu: "50m"
          volumeMounts:
            - name: apps
              mountPath: /var/www/html/custom_apps
            - name: config
              mountPath: /var/www/html/config
            - name: data
              mountPath: /var/www/html/data
            - name: html
              mountPath: /var/www/html
      volumes:
        - name: apps
          persistentVolumeClaim:
            claimName: nextcloud-apps
        - name: config
          persistentVolumeClaim:
            claimName: nextcloud-config
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-data
        - name: html
          persistentVolumeClaim:
            claimName: nextcloud-html

# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: nextcloud
#   namespace: nextcloud
#   annotations:
#     kubernetes.io/ingress.class: traefik-external
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`nextcloud.domain.com`)
#       kind: Rule
#       services:
#         - name: nextcloud
#           port: ##chosen_traefik_port
#       middlewares:
#         - name: default-headers
#         - name: nextcloud-redirectregex
#   tls:
#     secretName: prod-yourdomain-tls

---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - name: http
      protocol: TCP
      targetPort: 80
      port: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  namespace: nextcloud
  annotations:
    spec.ingressClassName: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10g"
spec:
  rules:
    - host: nextcloud.sharmahome.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  number: 80

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-apps
  namespace: nextcloud
spec:
  capacity:
    storage: 10Gi
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/Data/NextCloud/apps

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config
  namespace: nextcloud
spec:
  capacity:
    storage: 10Gi
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/Data/NextCloud/config

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  capacity:
    storage: 500Gi
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/Data/NextCloud/data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-html
  namespace: nextcloud
spec:
  capacity:
    storage: 10Gi
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/Data/NextCloud/html

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-apps
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: nextcloud-apps

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: nextcloud-config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: nextcloud-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-html
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: nextcloud-html
