apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: nextcloud
  labels:
    app: redis
spec:
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-redis
  namespace: nextcloud
spec:
  capacity:
    storage: 10Gi
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes-volumes/nextcloud/redis

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: nextcloud-redis

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: nextcloud
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
