apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-mariadb
  namespace: nextcloud
spec:
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes-volumes/nextcloud/mariadb

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-redis
  namespace: nextcloud
spec:
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes-volumes/nextcloud/redis

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-apps
  namespace: nextcloud
spec:
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes-volumes/nextcloud/apps

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config
  namespace: nextcloud
spec:
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes-volumes/nextcloud/config

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-html
  namespace: nextcloud
spec:
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes-volumes/nextcloud/html

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  storageClassName: "nfs"
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.1
    path: /mnt/Data/NextCloud/data
