apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-mariadb
  namespace: nextcloud
spec:
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes-volumes/nextcloud/mariadb

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-redis
  namespace: nextcloud
spec:
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes-volumes/nextcloud/redis

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-apps
  namespace: nextcloud
spec:
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes-volumes/nextcloud/apps

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config
  namespace: nextcloud
spec:
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes-volumes/nextcloud/config

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-html
  namespace: nextcloud
spec:
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes-volumes/nextcloud/html

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  storageClassName: "nfs"
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.1
    path: /mnt/Data/NextCloud/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: nextcloud
spec:
  volumeName: nextcloud-mariadb
  storageClassName: hostpath-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: nextcloud
spec:
  volumeName: nextcloud-redis
  storageClassName: hostpath-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps
  namespace: nextcloud
spec:
  volumeName: nextcloud-apps
  storageClassName: hostpath-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: nextcloud
spec:
  volumeName: nextcloud-config
  storageClassName: hostpath-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html
  namespace: nextcloud
spec:
  volumeName: nextcloud-html
  storageClassName: hostpath-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: nextcloud
spec:
  volumeName: nextcloud-data
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
