kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hostpath-storage
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /home/shared/kubernetes-volumes
volumeBindingMode: WaitForFirstConsumer
