services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: <USERID>:<USERID>
    network_mode: 'host'
    volumes:
      - ./config:/config
      - ./cache:/cache
      - <PATH/TO/MEDIA>:/media
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://<IPADDRESSORDOMAIN>
    extra_hosts:
      - "host.docker.internal:host-gateway"