apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  capacity:
    storage: 1Gi
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes-volumes/jellyfin/config

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache
  namespace: jellyfin
spec:
  capacity:
    storage: 1Gi
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/kubernetes-volumes/jellyfin/cache

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  storageClassName: "nfs"
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.1
    path: /mnt/Content
