apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  capacity:
    storage: 1Gi
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/Data/Jellyfin/config

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache
  namespace: jellyfin
spec:
  capacity:
    storage: 10Gi
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/Data/Jellyfin/cache

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  capacity:
    storage: 500Gi
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/Content

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  resources:
    requests:
      storage: 1Gi
  volumeName: jellyfin-config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  resources:
    requests:
      storage: 1Gi
  volumeName: jellyfin-cache

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  resources:
    requests:
      storage: 500Gi
  volumeName: jellyfin-media
