apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-jellyfin-config
  namespace: prod-jellyfin
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  hostPath:
    path: /opt/kubernetes-volumes/prod-jellyfin/config

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-jellyfin-cache
  namespace: prod-jellyfin
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  hostPath:
    path: /opt/kubernetes-volumes/prod-jellyfin/cache

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-jellyfin-media
  namespace: prod-jellyfin
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  # storageClassName: "nfs"
  # nfs:
  #   server: 10.0.0.1
  #   path: /mnt/Data/NextCloud/data
  storageClassName: hostpath-storage
  hostPath:
    path: /mnt/Content

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: prod-jellyfin
spec:
  volumeName: jellyfin-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
  namespace: prod-jellyfin
spec:
  volumeName: jellyfin-cache
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: prod-jellyfin
spec:
  volumeName: jellyfin-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  # storageClassName: nfs
  storageClassName: hostpath-storage
