kind: Deployment
apiVersion: apps/v1
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
  annotations: ## Add this annotations for keel ## 
    keel.sh/policy: minor
    keel.sh/trigger: poll    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
      - image: grafana/grafana:latest
        name: grafana
        env:
        - name: GF_PATHS_DATA
          value: "/var/lib/grafana"
        - name: GF_DEFAULT_INSTANCE_NAME
          value: "home"
        - name: TZ
          value: "Asia/Tokyo" 
        - name: GF_ANALYTICS_REPORTING_ENABLED
          value: "false"
        - name: GF_SERVER_ENABLE_GZIP
          value: "true"
        - name: GF_INSTALL_PLUGINS
          value: "grafana-clock-panel,grafana-simple-json-datasource,natel-plotly-panel,grafana-worldmap-panel,grafana-piechart-panel"
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /robots.txt
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 400Mi
        volumeMounts:
        - name: config
          mountPath: /var/lib/grafana
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-grafana

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - name: http
      targetPort: 3000
      port: 4000
