apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-mariadb
  namespace: stage-nextcloud
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  hostPath:
    path: /opt/kubernetes-volumes/stage-nextcloud/mariadb

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-redis
  namespace: stage-nextcloud
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  hostPath:
    path: /opt/kubernetes-volumes/stage-nextcloud/redis

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-apps
  namespace: stage-nextcloud
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  hostPath:
    path: /opt/kubernetes-volumes/stage-nextcloud/apps

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config
  namespace: stage-nextcloud
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  hostPath:
    path: /opt/kubernetes-volumes/stage-nextcloud/config

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-html
  namespace: stage-nextcloud
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage
  hostPath:
    path: /opt/kubernetes-volumes/stage-nextcloud/html

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  namespace: stage-nextcloud
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  # storageClassName: "nfs"
  # nfs:
  #   server: 10.0.0.1
  #   path: /mnt/Data/NextCloud/data
  storageClassName: hostpath-storage
  hostPath:
    path: /mnt/Data/NextCloud/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: stage-nextcloud
spec:
  volumeName: nextcloud-mariadb
  storageClassName: hostpath-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: stage-nextcloud
spec:
  volumeName: nextcloud-redis
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps
  namespace: stage-nextcloud
spec:
  volumeName: nextcloud-apps
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: stage-nextcloud
spec:
  volumeName: nextcloud-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html
  namespace: stage-nextcloud
spec:
  volumeName: nextcloud-html
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: stage-nextcloud
spec:
  volumeName: nextcloud-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  # storageClassName: nfs
  storageClassName: hostpath-storage
